language: java
addons:
  sonarcloud:
    organization: liutaurasvilda-github
    token:
      secure: ec68dd1107797373cff334e8d60c620750719961
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
